import { expect, test } from '@playwright/test'

const fixture = '/e2e/accessibility-controls/index.html'
test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.clear()
    localStorage.setItem('event-view-mode', JSON.stringify('grid'))
  })
  await page.route('**/*', (route) => {
    const url = new URL(route.request().url())
    if (url.origin !== 'http://127.0.0.1:15310') return route.abort()
    if (url.pathname === '/api/events' || url.pathname === '/api/event-groups') return route.fulfill({ json: [] })
    if (url.pathname.startsWith('/api/')) return route.abort()
    return route.continue()
  })
})
test('menu_escape_restores_focus', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto(fixture)
  const trigger = page.getByRole('button', { name: 'メニューを開く', exact: true })
  await trigger.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('link', { name: 'イベント', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'メニュー', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '操作確認', exact: true })).toHaveCount(0)
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'ログイン', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(page.getByRole('link', { name: 'イベント', exact: true })).toHaveCount(0)
})
test('closed_sort_has_no_focusable_options', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto(fixture)
  const toggle = page.getByRole('button', { name: /^並び替え:/ })
  await expect(page.getByRole('button', { name: /^(ランダム|誕生日順|開店日順|誕生日が近い順)$/ })).toHaveCount(0)
  await toggle.focus()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: '前の月', exact: true })).toBeFocused()
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('button', { name: 'ランダム', exact: true }).click()
  await expect(page.getByLabel('ランダム回数')).toHaveText('1')
  await expect(toggle).toBeFocused()
  await expect(page.getByRole('button', { name: /^(ランダム|誕生日順|開店日順|誕生日が近い順)$/ })).toHaveCount(0)
})
test('controls_have_names_and_selected_state', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto(fixture)
  await expect(page.getByRole('radio', { name: '全国', exact: true })).toBeChecked()
  const hokkaido = page.getByRole('radio', { name: '北海道', exact: true })
  await hokkaido.click()
  await expect(hokkaido).toBeChecked()
  // Radix defers roving focus; hold the key through the focus/selection event.
  await page.keyboard.down('ArrowRight')
  await expect(page.getByRole('radio', { name: '関東', exact: true })).toBeChecked()
  await page.keyboard.up('ArrowRight')
  await expect(page.getByRole('button', { name: '10月', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '次の月', exact: true }).click()
  await expect(page.getByRole('button', { name: '11月', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '前の月', exact: true }).click()
  await expect(page.getByRole('button', { name: '10月', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('combobox', { name: '札幌店の利用駅', exact: true }).click()
  await page.getByRole('option', { name: '大通', exact: true }).click()
  await expect(page.getByRole('combobox', { name: '札幌店の利用駅', exact: true })).toHaveText('大通')
  await page.getByRole('button', { name: '札幌店をルートから削除', exact: true }).click()
  await expect(page.getByText('札幌店', { exact: true })).toHaveCount(0)
})
test('desktop_sort_remains_visible', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto(fixture)
  const random = page.getByRole('button', { name: 'ランダム', exact: true })
  await expect(random).toBeVisible()
  await random.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('ランダム回数')).toHaveText('1')
  await expect(random).toBeVisible()
})
test('menu_keyboard_navigation_closes_and_restores_focus', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto(fixture)
  const trigger = page.getByRole('button', { name: 'メニューを開く', exact: true })
  await trigger.click()
  const link = page.getByRole('link', { name: 'ビッカメ娘', exact: true }).last()
  await link.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'ビッカメ娘一覧' })).toBeVisible()
  await expect(trigger).toBeFocused()
})
test('event_controls_have_exact_action_names', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto(`${fixture}?path=/events/`)
  const filter = page.getByRole('button', { name: 'イベントを絞り込む', exact: true })
  await filter.click()
  await expect(page.getByRole('dialog', { name: 'フィルター', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(filter).toBeFocused()
  const scheduleAction = page.getByRole('button', { name: '日程表示', exact: true })
  // A next-action command must not announce that the opposite view is pressed.
  await expect(scheduleAction).not.toHaveAttribute('aria-pressed', 'true')
  await scheduleAction.click()
  await expect.poll(() => page.evaluate(() => localStorage.getItem('event-view-mode'))).toBe(JSON.stringify('gantt'))
  const listAction = page.getByRole('button', { name: '一覧表示', exact: true })
  await expect(listAction).not.toHaveAttribute('aria-pressed', 'true')
  await listAction.click()
  await expect.poll(() => page.evaluate(() => localStorage.getItem('event-view-mode'))).toBe(JSON.stringify('grid'))
  await expect(page.getByRole('button', { name: '日程表示', exact: true })).toBeVisible()
})

test('mobile_region_and_month_expose_selected_state', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto(fixture)
  await expect(page.getByRole('radiogroup', { name: '地域で絞り込み', exact: true })).toBeVisible()
  await expect(page.getByRole('radio', { name: '全国', exact: true })).toBeChecked()
  await page.getByRole('radio', { name: '北海道', exact: true }).click()
  await expect(page.getByRole('radio', { name: '北海道', exact: true })).toBeChecked()
  await expect(page.getByRole('radio', { name: '全国', exact: true })).not.toBeChecked()
  await expect(page.getByRole('button', { name: '10月に移動', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '11月に移動', exact: true }).click()
  await expect(page.getByRole('button', { name: '11月に移動', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: '10月に移動', exact: true })).toHaveAttribute('aria-pressed', 'false')
})
