/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RouteIndexRouteImport } from './routes/route/index'
import { Route as RankingIndexRouteImport } from './routes/ranking/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as LocationIndexRouteImport } from './routes/location/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as BadgesIndexRouteImport } from './routes/badges/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as MeVisitedIndexRouteImport } from './routes/me/visited/index'
import { Route as MeInterestedIndexRouteImport } from './routes/me/interested/index'
import { Route as MeFavoritesIndexRouteImport } from './routes/me/favorites/index'
import { Route as MeCompletedIndexRouteImport } from './routes/me/completed/index'
import { Route as EventsUuidIndexRouteImport } from './routes/events/$uuid/index'
import { Route as CharactersIdIndexRouteImport } from './routes/characters/$id/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTwitterIndexRouteImport } from './routes/admin/twitter/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventGroupsIndexRouteImport } from './routes/admin/event-groups/index'
import { Route as AdminCommentsIndexRouteImport } from './routes/admin/comments/index'
import { Route as AdminBadgesIndexRouteImport } from './routes/admin/badges/index'
import { Route as EventsGroupSlugIndexRouteImport } from './routes/events/group/$slug/index'
import { Route as AdminEventsNewIndexRouteImport } from './routes/admin/events/new/index'
import { Route as AdminEventsUuidIndexRouteImport } from './routes/admin/events/$uuid/index'
import { Route as AdminEventGroupsNewIndexRouteImport } from './routes/admin/event-groups/new/index'
import { Route as AdminEventsUuidEditIndexRouteImport } from './routes/admin/events/$uuid/edit/index'
import { Route as AdminEventGroupsUuidEditIndexRouteImport } from './routes/admin/event-groups/$uuid/edit/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteIndexRoute = RouteIndexRouteImport.update({
  id: '/route/',
  path: '/route/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationIndexRoute = LocationIndexRouteImport.update({
  id: '/location/',
  path: '/location/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesIndexRoute = BadgesIndexRouteImport.update({
  id: '/badges/',
  path: '/badges/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeVisitedIndexRoute = MeVisitedIndexRouteImport.update({
  id: '/me/visited/',
  path: '/me/visited/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeInterestedIndexRoute = MeInterestedIndexRouteImport.update({
  id: '/me/interested/',
  path: '/me/interested/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeFavoritesIndexRoute = MeFavoritesIndexRouteImport.update({
  id: '/me/favorites/',
  path: '/me/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeCompletedIndexRoute = MeCompletedIndexRouteImport.update({
  id: '/me/completed/',
  path: '/me/completed/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsUuidIndexRoute = EventsUuidIndexRouteImport.update({
  id: '/events/$uuid/',
  path: '/events/$uuid/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdIndexRoute = CharactersIdIndexRouteImport.update({
  id: '/characters/$id/',
  path: '/characters/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTwitterIndexRoute = AdminTwitterIndexRouteImport.update({
  id: '/twitter/',
  path: '/twitter/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventGroupsIndexRoute = AdminEventGroupsIndexRouteImport.update({
  id: '/event-groups/',
  path: '/event-groups/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsIndexRoute = AdminCommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBadgesIndexRoute = AdminBadgesIndexRouteImport.update({
  id: '/badges/',
  path: '/badges/',
  getParentRoute: () => AdminRoute,
} as any)
const EventsGroupSlugIndexRoute = EventsGroupSlugIndexRouteImport.update({
  id: '/events/group/$slug/',
  path: '/events/group/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsNewIndexRoute = AdminEventsNewIndexRouteImport.update({
  id: '/events/new/',
  path: '/events/new/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsUuidIndexRoute = AdminEventsUuidIndexRouteImport.update({
  id: '/events/$uuid/',
  path: '/events/$uuid/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventGroupsNewIndexRoute =
  AdminEventGroupsNewIndexRouteImport.update({
    id: '/event-groups/new/',
    path: '/event-groups/new/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsUuidEditIndexRoute =
  AdminEventsUuidEditIndexRouteImport.update({
    id: '/events/$uuid/edit/',
    path: '/events/$uuid/edit/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventGroupsUuidEditIndexRoute =
  AdminEventGroupsUuidEditIndexRouteImport.update({
    id: '/event-groups/$uuid/edit/',
    path: '/event-groups/$uuid/edit/',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/badges/': typeof BadgesIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/events/': typeof EventsIndexRoute
  '/location/': typeof LocationIndexRoute
  '/me/': typeof MeIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/route/': typeof RouteIndexRoute
  '/admin/badges/': typeof AdminBadgesIndexRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/event-groups/': typeof AdminEventGroupsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/twitter/': typeof AdminTwitterIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/characters/$id/': typeof CharactersIdIndexRoute
  '/events/$uuid/': typeof EventsUuidIndexRoute
  '/me/completed/': typeof MeCompletedIndexRoute
  '/me/favorites/': typeof MeFavoritesIndexRoute
  '/me/interested/': typeof MeInterestedIndexRoute
  '/me/visited/': typeof MeVisitedIndexRoute
  '/admin/event-groups/new/': typeof AdminEventGroupsNewIndexRoute
  '/admin/events/$uuid/': typeof AdminEventsUuidIndexRoute
  '/admin/events/new/': typeof AdminEventsNewIndexRoute
  '/events/group/$slug/': typeof EventsGroupSlugIndexRoute
  '/admin/event-groups/$uuid/edit/': typeof AdminEventGroupsUuidEditIndexRoute
  '/admin/events/$uuid/edit/': typeof AdminEventsUuidEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/badges': typeof BadgesIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/contact': typeof ContactIndexRoute
  '/events': typeof EventsIndexRoute
  '/location': typeof LocationIndexRoute
  '/me': typeof MeIndexRoute
  '/ranking': typeof RankingIndexRoute
  '/route': typeof RouteIndexRoute
  '/admin/badges': typeof AdminBadgesIndexRoute
  '/admin/comments': typeof AdminCommentsIndexRoute
  '/admin/event-groups': typeof AdminEventGroupsIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/twitter': typeof AdminTwitterIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/characters/$id': typeof CharactersIdIndexRoute
  '/events/$uuid': typeof EventsUuidIndexRoute
  '/me/completed': typeof MeCompletedIndexRoute
  '/me/favorites': typeof MeFavoritesIndexRoute
  '/me/interested': typeof MeInterestedIndexRoute
  '/me/visited': typeof MeVisitedIndexRoute
  '/admin/event-groups/new': typeof AdminEventGroupsNewIndexRoute
  '/admin/events/$uuid': typeof AdminEventsUuidIndexRoute
  '/admin/events/new': typeof AdminEventsNewIndexRoute
  '/events/group/$slug': typeof EventsGroupSlugIndexRoute
  '/admin/event-groups/$uuid/edit': typeof AdminEventGroupsUuidEditIndexRoute
  '/admin/events/$uuid/edit': typeof AdminEventsUuidEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/badges/': typeof BadgesIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/events/': typeof EventsIndexRoute
  '/location/': typeof LocationIndexRoute
  '/me/': typeof MeIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/route/': typeof RouteIndexRoute
  '/admin/badges/': typeof AdminBadgesIndexRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/event-groups/': typeof AdminEventGroupsIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/twitter/': typeof AdminTwitterIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/characters/$id/': typeof CharactersIdIndexRoute
  '/events/$uuid/': typeof EventsUuidIndexRoute
  '/me/completed/': typeof MeCompletedIndexRoute
  '/me/favorites/': typeof MeFavoritesIndexRoute
  '/me/interested/': typeof MeInterestedIndexRoute
  '/me/visited/': typeof MeVisitedIndexRoute
  '/admin/event-groups/new/': typeof AdminEventGroupsNewIndexRoute
  '/admin/events/$uuid/': typeof AdminEventsUuidIndexRoute
  '/admin/events/new/': typeof AdminEventsNewIndexRoute
  '/events/group/$slug/': typeof EventsGroupSlugIndexRoute
  '/admin/event-groups/$uuid/edit/': typeof AdminEventGroupsUuidEditIndexRoute
  '/admin/events/$uuid/edit/': typeof AdminEventsUuidEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about/'
    | '/admin/'
    | '/badges/'
    | '/calendar/'
    | '/characters/'
    | '/contact/'
    | '/events/'
    | '/location/'
    | '/me/'
    | '/ranking/'
    | '/route/'
    | '/admin/badges/'
    | '/admin/comments/'
    | '/admin/event-groups/'
    | '/admin/events/'
    | '/admin/twitter/'
    | '/admin/users/'
    | '/characters/$id/'
    | '/events/$uuid/'
    | '/me/completed/'
    | '/me/favorites/'
    | '/me/interested/'
    | '/me/visited/'
    | '/admin/event-groups/new/'
    | '/admin/events/$uuid/'
    | '/admin/events/new/'
    | '/events/group/$slug/'
    | '/admin/event-groups/$uuid/edit/'
    | '/admin/events/$uuid/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/badges'
    | '/calendar'
    | '/characters'
    | '/contact'
    | '/events'
    | '/location'
    | '/me'
    | '/ranking'
    | '/route'
    | '/admin/badges'
    | '/admin/comments'
    | '/admin/event-groups'
    | '/admin/events'
    | '/admin/twitter'
    | '/admin/users'
    | '/characters/$id'
    | '/events/$uuid'
    | '/me/completed'
    | '/me/favorites'
    | '/me/interested'
    | '/me/visited'
    | '/admin/event-groups/new'
    | '/admin/events/$uuid'
    | '/admin/events/new'
    | '/events/group/$slug'
    | '/admin/event-groups/$uuid/edit'
    | '/admin/events/$uuid/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about/'
    | '/admin/'
    | '/badges/'
    | '/calendar/'
    | '/characters/'
    | '/contact/'
    | '/events/'
    | '/location/'
    | '/me/'
    | '/ranking/'
    | '/route/'
    | '/admin/badges/'
    | '/admin/comments/'
    | '/admin/event-groups/'
    | '/admin/events/'
    | '/admin/twitter/'
    | '/admin/users/'
    | '/characters/$id/'
    | '/events/$uuid/'
    | '/me/completed/'
    | '/me/favorites/'
    | '/me/interested/'
    | '/me/visited/'
    | '/admin/event-groups/new/'
    | '/admin/events/$uuid/'
    | '/admin/events/new/'
    | '/events/group/$slug/'
    | '/admin/event-groups/$uuid/edit/'
    | '/admin/events/$uuid/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  BadgesIndexRoute: typeof BadgesIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LocationIndexRoute: typeof LocationIndexRoute
  MeIndexRoute: typeof MeIndexRoute
  RankingIndexRoute: typeof RankingIndexRoute
  RouteIndexRoute: typeof RouteIndexRoute
  CharactersIdIndexRoute: typeof CharactersIdIndexRoute
  EventsUuidIndexRoute: typeof EventsUuidIndexRoute
  MeCompletedIndexRoute: typeof MeCompletedIndexRoute
  MeFavoritesIndexRoute: typeof MeFavoritesIndexRoute
  MeInterestedIndexRoute: typeof MeInterestedIndexRoute
  MeVisitedIndexRoute: typeof MeVisitedIndexRoute
  EventsGroupSlugIndexRoute: typeof EventsGroupSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route/': {
      id: '/route/'
      path: '/route'
      fullPath: '/route/'
      preLoaderRoute: typeof RouteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/': {
      id: '/ranking/'
      path: '/ranking'
      fullPath: '/ranking/'
      preLoaderRoute: typeof RankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/': {
      id: '/location/'
      path: '/location'
      fullPath: '/location/'
      preLoaderRoute: typeof LocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges/': {
      id: '/badges/'
      path: '/badges'
      fullPath: '/badges/'
      preLoaderRoute: typeof BadgesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/visited/': {
      id: '/me/visited/'
      path: '/me/visited'
      fullPath: '/me/visited/'
      preLoaderRoute: typeof MeVisitedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/interested/': {
      id: '/me/interested/'
      path: '/me/interested'
      fullPath: '/me/interested/'
      preLoaderRoute: typeof MeInterestedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/favorites/': {
      id: '/me/favorites/'
      path: '/me/favorites'
      fullPath: '/me/favorites/'
      preLoaderRoute: typeof MeFavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/completed/': {
      id: '/me/completed/'
      path: '/me/completed'
      fullPath: '/me/completed/'
      preLoaderRoute: typeof MeCompletedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$uuid/': {
      id: '/events/$uuid/'
      path: '/events/$uuid'
      fullPath: '/events/$uuid/'
      preLoaderRoute: typeof EventsUuidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id/': {
      id: '/characters/$id/'
      path: '/characters/$id'
      fullPath: '/characters/$id/'
      preLoaderRoute: typeof CharactersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/twitter/': {
      id: '/admin/twitter/'
      path: '/twitter'
      fullPath: '/admin/twitter/'
      preLoaderRoute: typeof AdminTwitterIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/event-groups/': {
      id: '/admin/event-groups/'
      path: '/event-groups'
      fullPath: '/admin/event-groups/'
      preLoaderRoute: typeof AdminEventGroupsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments/': {
      id: '/admin/comments/'
      path: '/comments'
      fullPath: '/admin/comments/'
      preLoaderRoute: typeof AdminCommentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/badges/': {
      id: '/admin/badges/'
      path: '/badges'
      fullPath: '/admin/badges/'
      preLoaderRoute: typeof AdminBadgesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/group/$slug/': {
      id: '/events/group/$slug/'
      path: '/events/group/$slug'
      fullPath: '/events/group/$slug/'
      preLoaderRoute: typeof EventsGroupSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/new/': {
      id: '/admin/events/new/'
      path: '/events/new'
      fullPath: '/admin/events/new/'
      preLoaderRoute: typeof AdminEventsNewIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$uuid/': {
      id: '/admin/events/$uuid/'
      path: '/events/$uuid'
      fullPath: '/admin/events/$uuid/'
      preLoaderRoute: typeof AdminEventsUuidIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/event-groups/new/': {
      id: '/admin/event-groups/new/'
      path: '/event-groups/new'
      fullPath: '/admin/event-groups/new/'
      preLoaderRoute: typeof AdminEventGroupsNewIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$uuid/edit/': {
      id: '/admin/events/$uuid/edit/'
      path: '/events/$uuid/edit'
      fullPath: '/admin/events/$uuid/edit/'
      preLoaderRoute: typeof AdminEventsUuidEditIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/event-groups/$uuid/edit/': {
      id: '/admin/event-groups/$uuid/edit/'
      path: '/event-groups/$uuid/edit'
      fullPath: '/admin/event-groups/$uuid/edit/'
      preLoaderRoute: typeof AdminEventGroupsUuidEditIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBadgesIndexRoute: typeof AdminBadgesIndexRoute
  AdminCommentsIndexRoute: typeof AdminCommentsIndexRoute
  AdminEventGroupsIndexRoute: typeof AdminEventGroupsIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminTwitterIndexRoute: typeof AdminTwitterIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminEventGroupsNewIndexRoute: typeof AdminEventGroupsNewIndexRoute
  AdminEventsUuidIndexRoute: typeof AdminEventsUuidIndexRoute
  AdminEventsNewIndexRoute: typeof AdminEventsNewIndexRoute
  AdminEventGroupsUuidEditIndexRoute: typeof AdminEventGroupsUuidEditIndexRoute
  AdminEventsUuidEditIndexRoute: typeof AdminEventsUuidEditIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBadgesIndexRoute: AdminBadgesIndexRoute,
  AdminCommentsIndexRoute: AdminCommentsIndexRoute,
  AdminEventGroupsIndexRoute: AdminEventGroupsIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminTwitterIndexRoute: AdminTwitterIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminEventGroupsNewIndexRoute: AdminEventGroupsNewIndexRoute,
  AdminEventsUuidIndexRoute: AdminEventsUuidIndexRoute,
  AdminEventsNewIndexRoute: AdminEventsNewIndexRoute,
  AdminEventGroupsUuidEditIndexRoute: AdminEventGroupsUuidEditIndexRoute,
  AdminEventsUuidEditIndexRoute: AdminEventsUuidEditIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  BadgesIndexRoute: BadgesIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  LocationIndexRoute: LocationIndexRoute,
  MeIndexRoute: MeIndexRoute,
  RankingIndexRoute: RankingIndexRoute,
  RouteIndexRoute: RouteIndexRoute,
  CharactersIdIndexRoute: CharactersIdIndexRoute,
  EventsUuidIndexRoute: EventsUuidIndexRoute,
  MeCompletedIndexRoute: MeCompletedIndexRoute,
  MeFavoritesIndexRoute: MeFavoritesIndexRoute,
  MeInterestedIndexRoute: MeInterestedIndexRoute,
  MeVisitedIndexRoute: MeVisitedIndexRoute,
  EventsGroupSlugIndexRoute: EventsGroupSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
