services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules:/home/vscode/app/node_modules
      - ../:/home/vscode/app:cached
    environment:
      NODE_ENV: development
    tty: true
    stdin_open: true
    network_mode: service:firebase
    depends_on:
      - firebase

  firebase:
    image: andreysenov/firebase-tools:14.17.0
    environment:
      FIREBASE_TOKEN: $FIREBASE_TOKEN
    command: firebase emulators:start --only auth --import=auth
    volumes:
      - ./auth:/home/node/auth
      - ./firebase.json:/home/node/firebase.json
      - ./.firebaserc:/home/node/.firebaserc

volumes:
  node_modules:
