import { z } from 'zod'

export const FeaturesSchema = z
  .object({
    rweb_video_screen_enabled: z.boolean().default(false),
    profile_label_improvements_pcf_label_in_post_enabled: z.boolean().default(true),
    responsive_web_profile_redirect_enabled: z.boolean().default(false),
    rweb_tipjar_consumption_enabled: z.boolean().default(false),
    verified_phone_label_enabled: z.boolean().default(false),
    creator_subscriptions_tweet_preview_api_enabled: z.boolean().default(true),
    responsive_web_graphql_timeline_navigation_enabled: z.boolean().default(true),
    responsive_web_graphql_skip_user_profile_image_extensions_enabled: z.boolean().default(false),
    premium_content_api_read_enabled: z.boolean().default(false),
    communities_web_enable_tweet_community_results_fetch: z.boolean().default(true),
    c9s_tweet_anatomy_moderator_badge_enabled: z.boolean().default(true),
    responsive_web_grok_analyze_button_fetch_trends_enabled: z.boolean().default(false),
    responsive_web_grok_analyze_post_followups_enabled: z.boolean().default(true),
    responsive_web_jetfuel_frame: z.boolean().default(true),
    responsive_web_grok_share_attachment_enabled: z.boolean().default(true),
    responsive_web_grok_annotations_enabled: z.boolean().default(false),
    articles_preview_enabled: z.boolean().default(true),
    responsive_web_edit_tweet_api_enabled: z.boolean().default(true),
    graphql_is_translatable_rweb_tweet_is_translatable_enabled: z.boolean().default(true),
    view_counts_everywhere_api_enabled: z.boolean().default(true),
    longform_notetweets_consumption_enabled: z.boolean().default(true),
    responsive_web_twitter_article_tweet_consumption_enabled: z.boolean().default(true),
    tweet_awards_web_tipping_enabled: z.boolean().default(false),
    responsive_web_grok_show_grok_translated_post: z.boolean().default(false),
    responsive_web_grok_analysis_button_from_backend: z.boolean().default(true),
    post_ctas_fetch_enabled: z.boolean().default(true),
    creator_subscriptions_quote_tweet_preview_enabled: z.boolean().default(false),
    freedom_of_speech_not_reach_fetch_enabled: z.boolean().default(true),
    standardized_nudges_misinfo: z.boolean().default(true),
    tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled: z.boolean().default(true),
    longform_notetweets_rich_text_read_enabled: z.boolean().default(true),
    longform_notetweets_inline_media_enabled: z.boolean().default(true),
    responsive_web_grok_image_annotation_enabled: z.boolean().default(true),
    responsive_web_grok_imagine_annotation_enabled: z.boolean().default(true),
    responsive_web_grok_community_note_auto_translation_is_enabled: z.boolean().default(false),
    responsive_web_enhance_cards_enabled: z.boolean().default(false)
  })
  .transform((v) => JSON.stringify(v))
